-- Creazione del plugin
-- INSERT INTO `zz_plugins` (`name`, `title`, `idmodule_from`, `idmodule_to`, `position`, `script`, `enabled`, `default`, `order`, `compatibility`, `version`, `options2`, `options`, `directory`, `help`) VALUES ('Crea Vendita', 'Crea Vendita', (SELECT `zz_modules`.`id` FROM `zz_modules` WHERE `zz_modules`.`name`='Preventivi'), (SELECT `zz_modules`.`id` FROM `zz_modules` WHERE `zz_modules`.`name`='Preventivi'), 'tab', '', '1', '0', '0', '', '', NULL, 'custom', 'crea_vendita', '');

INSERT INTO `zz_plugins` (`name`, `title`, `idmodule_from`, `idmodule_to`, `position`, `script`, `enabled`, `default`, `order`, `compatibility`, `version`, `options2`, `options`, `directory`, `help`) VALUES ('Crea Vendita', 'Crea Vendita', (SELECT `zz_modules`.`id` FROM `zz_modules` WHERE `zz_modules`.`name`='Interventi'), (SELECT `zz_modules`.`id` FROM `zz_modules` WHERE `zz_modules`.`name`='Interventi'), 'tab', '', '1', '0', '0', '', '', NULL, 'custom', 'crea_vendita', '');

INSERT INTO `zz_plugins` (`name`, `title`, `idmodule_from`, `idmodule_to`, `position`, `script`, `enabled`, `default`, `order`, `compatibility`, `version`, `options2`, `options`, `directory`, `help`) VALUES ('Crea Vendita', 'Crea Vendita', (SELECT `zz_modules`.`id` FROM `zz_modules` WHERE `zz_modules`.`name`='Ordini cliente'), (SELECT `zz_modules`.`id` FROM `zz_modules` WHERE `zz_modules`.`name`='Ordini cliente'), 'tab', '', '1', '0', '0', '', '', NULL, 'custom', 'crea_vendita', '');

INSERT INTO `zz_plugins` (`name`, `title`, `idmodule_from`, `idmodule_to`, `position`, `script`, `enabled`, `default`, `order`, `compatibility`, `version`, `options2`, `options`, `directory`, `help`) VALUES ('Crea Vendita', 'Crea Vendita', (SELECT `zz_modules`.`id` FROM `zz_modules` WHERE `zz_modules`.`name`='Ddt di vendita'), (SELECT `zz_modules`.`id` FROM `zz_modules` WHERE `zz_modules`.`name`='Ddt di vendita'), 'tab', '', '1', '0', '0', '', '', NULL, 'custom', 'crea_vendita', '');

ALTER TABLE `vb_righe_venditabanco` ADD `original_id` INT NULL DEFAULT NULL AFTER `abilita_serial`, ADD `original_type` VARCHAR(255) NULL DEFAULT NULL AFTER `original_id`, ADD `idintervento` INT NULL DEFAULT NULL AFTER `original_type`;
